FROM python:3.8-slim

# Install curl
RUN apt-get update && apt-get install -y curl

WORKDIR /app

COPY . /app

RUN pip install --no-cache-dir -r requirements.txt

EXPOSE 5000

CMD ["python", "ordering_service.py"]
